version: '3.0' 

services:
  zuthaka:
    build:
      context: .
    network_mode: host
    user: pucara
    command: gunicorn zuthaka.wsgi:application --bind 127.0.0.1:8080
    container_name: Zuthaka_backend
  redis:
    image: redis:5
    network_mode: host
  nginx:
    image: nginx:1.19
    ports:
      - 80:80
    volumes:
      - ./Volumes/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Volumes/build:/frontend/build
volumes:
  build_folder:

